import { target } from "./_target";
import type { TargetTool } from "../../schema";

/** Office/documents and file sharing — the two categories that touch every seat. */
export const collaborationTargets: TargetTool[] = [
  // --- Office and documents -------------------------------------------------
  target({
    id: "collabora-online",
    category: "office_docs",
    name: "Collabora Online",
    summary: {
      de: "Gemeinsames Bearbeiten von Dokumenten im Browser, aufbauend auf LibreOffice. Wird meist zusammen mit einer Dateiablage wie Nextcloud betrieben.",
      en: "Browser-based collaborative document editing built on LibreOffice, usually run alongside a file platform such as Nextcloud.",
    },
    license: "mpl",
    vendorCountry: "GB",
    ecosystem: "nextcloud",
    hostingModes: ["self_hosted", "eu_managed"],
    sovereignty: 5,
    maturity: 4,
    supportModel: "commercial_available",
    deMarketPresence: 4,
    germanUiQuality: 4,
    publicSectorFit: 4,
    selfHostOpsLoad: 3,
    migrationComplexityBase: 3,
    trainingLoad: 3,
    seatScalability: {
      comfortableUpTo: 1000,
      notes: {
        de: "Die Zahl gleichzeitig bearbeiteter Dokumente treibt den Ressourcenbedarf stärker als die Zahl der Konten. Ab mehreren hundert aktiven Bearbeitungen ist eine getrennte Dimensionierung nötig.",
        en: "Concurrent editing sessions drive resource needs more than account counts. Beyond a few hundred active editors, size the service separately.",
      },
    },
    coexistence: "good",
    rollbackDifficulty: 2,
    aiSuitability: { hasNativeAi: false, localAiFriendly: 3 },
    prerequisites: ["file-platform", "identity-directory"],
    sources: [
      "https://www.collaboraonline.com/",
      "https://sdk.collaboraonline.com/docs/installation/",
    ],
  }),
  target({
    id: "onlyoffice-docs",
    category: "office_docs",
    name: "ONLYOFFICE Docs",
    summary: {
      de: "Dokumentenbearbeitung im Browser mit enger Anlehnung an die Bedienung und Formate von Microsoft Office.",
      en: "Browser-based document editing with an interface and format handling close to Microsoft Office.",
    },
    license: "agpl",
    vendorCountry: "LV",
    hostingModes: ["self_hosted", "eu_managed"],
    sovereignty: 4,
    maturity: 4,
    supportModel: "commercial_available",
    deMarketPresence: 3,
    germanUiQuality: 4,
    publicSectorFit: 3,
    selfHostOpsLoad: 3,
    migrationComplexityBase: 2,
    trainingLoad: 2,
    seatScalability: {
      comfortableUpTo: 1000,
      notes: {
        de: "Die Nähe zur gewohnten Office-Bedienung senkt den Schulungsaufwand spürbar, was bei vielen Arbeitsplätzen stärker zählt als technische Feinheiten.",
        en: "Familiar Office-like handling noticeably lowers training effort, which matters more at scale than technical detail.",
      },
    },
    coexistence: "good",
    rollbackDifficulty: 2,
    aiSuitability: { hasNativeAi: false, localAiFriendly: 3 },
    prerequisites: ["file-platform"],
    sources: ["https://www.onlyoffice.com/", "https://helpcenter.onlyoffice.com/"],
  }),
  target({
    id: "libreoffice",
    category: "office_docs",
    name: "LibreOffice",
    summary: {
      de: "Klassisches Office-Paket zur lokalen Installation. Kein gemeinsames Echtzeit-Bearbeiten, dafür sehr geringer Betriebsaufwand.",
      en: "A classic locally installed office suite. No real-time co-editing, but very low operational overhead.",
    },
    license: "mpl",
    vendorCountry: "DE",
    hostingModes: ["local_device"],
    sovereignty: 5,
    maturity: 5,
    supportModel: "commercial_available",
    deMarketPresence: 5,
    germanUiQuality: 5,
    publicSectorFit: 4,
    selfHostOpsLoad: 1,
    migrationComplexityBase: 2,
    trainingLoad: 3,
    seatScalability: {
      comfortableUpTo: 100_000,
      notes: {
        de: "Skaliert über Softwareverteilung, nicht über Server. Der Aufwand wächst mit der Zahl der Endgeräte, nicht mit der Nutzung.",
        en: "Scales through software deployment rather than servers. Effort grows with device count, not usage.",
      },
    },
    coexistence: "good",
    rollbackDifficulty: 1,
    aiSuitability: { hasNativeAi: false, localAiFriendly: 2 },
    prerequisites: ["endpoint-management"],
    sources: ["https://www.libreoffice.org/", "https://www.documentfoundation.org/"],
  }),

  // --- File storage and sharing ---------------------------------------------
  target({
    id: "nextcloud",
    category: "file_sharing",
    name: "Nextcloud",
    summary: {
      de: "Dateiablage mit Synchronisation, Freigaben und einer breiten Erweiterungslandschaft. In Deutschland verbreitet und mit vielen Dienstleistern verfügbar.",
      en: "File platform with sync, sharing and a broad add-on ecosystem. Widely used in Germany with many service providers available.",
    },
    license: "agpl",
    vendorCountry: "DE",
    ecosystem: "nextcloud",
    hostingModes: ["self_hosted", "eu_managed"],
    sovereignty: 5,
    maturity: 4,
    supportModel: "vendor_backed",
    deMarketPresence: 5,
    germanUiQuality: 5,
    publicSectorFit: 4,
    selfHostOpsLoad: 3,
    migrationComplexityBase: 3,
    trainingLoad: 2,
    seatScalability: {
      comfortableUpTo: 2000,
      notes: {
        de: "Bis in den vierstelligen Bereich mit einer sorgfältig aufgesetzten Installation gut beherrschbar. Darüber hinaus sind getrennte Datenbank- und Speicherschichten sowie Betriebserfahrung nötig.",
        en: "Manageable into the low thousands with a carefully built install. Beyond that, separate database and storage tiers plus operational experience are needed.",
      },
    },
    coexistence: "good",
    rollbackDifficulty: 3,
    aiSuitability: {
      hasNativeAi: true,
      localAiFriendly: 4,
      notes: {
        de: "Assistenzfunktionen lassen sich mit selbst betriebenen oder EU-gehosteten Modellen verbinden, statt an einen externen Anbieter gebunden zu sein.",
        en: "Assistant features can be pointed at self-hosted or EU-hosted models rather than tied to an external provider.",
      },
    },
    prerequisites: ["identity-directory", "backup-restore"],
    sources: ["https://nextcloud.com/", "https://docs.nextcloud.com/"],
  }),
  target({
    id: "owncloud-infinite-scale",
    category: "file_sharing",
    name: "ownCloud Infinite Scale",
    summary: {
      de: "Neu aufgebaute Dateiplattform mit Fokus auf Betrieb in größeren Umgebungen.",
      en: "A rebuilt file platform focused on operating in larger environments.",
    },
    license: "apache",
    vendorCountry: "DE",
    hostingModes: ["self_hosted", "eu_managed"],
    sovereignty: 5,
    maturity: 3,
    supportModel: "vendor_backed",
    deMarketPresence: 4,
    germanUiQuality: 5,
    publicSectorFit: 3,
    selfHostOpsLoad: 3,
    migrationComplexityBase: 3,
    trainingLoad: 2,
    seatScalability: {
      comfortableUpTo: 5000,
      notes: {
        de: "Auf größere Installationen ausgelegt. Der Funktionsumfang rund um Erweiterungen ist schmaler als bei länger etablierten Alternativen.",
        en: "Designed for larger installs. The add-on surface is narrower than in longer-established alternatives.",
      },
    },
    coexistence: "good",
    rollbackDifficulty: 3,
    aiSuitability: { hasNativeAi: false, localAiFriendly: 3 },
    prerequisites: ["identity-directory", "backup-restore"],
    sources: ["https://owncloud.com/", "https://doc.owncloud.com/"],
  }),
  target({
    id: "seafile",
    category: "file_sharing",
    name: "Seafile",
    summary: {
      de: "Dateiablage mit Schwerpunkt auf schneller und zuverlässiger Synchronisation großer Datenmengen.",
      en: "File platform focused on fast, reliable synchronization of large data volumes.",
    },
    license: "open_core",
    vendorCountry: "DE",
    hostingModes: ["self_hosted", "eu_managed"],
    sovereignty: 4,
    maturity: 4,
    supportModel: "commercial_available",
    deMarketPresence: 3,
    germanUiQuality: 4,
    publicSectorFit: 3,
    selfHostOpsLoad: 2,
    migrationComplexityBase: 3,
    trainingLoad: 2,
    seatScalability: {
      comfortableUpTo: 3000,
      notes: {
        de: "Robuste Synchronisation auch bei vielen Dateien. Teile des Funktionsumfangs stehen nur in der kostenpflichtigen Ausgabe bereit — das ist bei der Planung zu berücksichtigen.",
        en: "Robust sync even with many files. Some functionality is only in the paid edition, which needs accounting for during planning.",
      },
    },
    coexistence: "good",
    rollbackDifficulty: 2,
    aiSuitability: { hasNativeAi: false, localAiFriendly: 2 },
    prerequisites: ["identity-directory", "backup-restore"],
    sources: ["https://www.seafile.com/", "https://manual.seafile.com/"],
  }),
];
