import { target } from "./_target";
import type { TargetTool } from "../../schema";

/** Chat/video and intranet/wiki — the categories where habits change hardest. */
export const communicationTargets: TargetTool[] = [
  // --- Chat and video -------------------------------------------------------
  target({
    id: "element-matrix",
    category: "chat_video",
    name: "Element (Matrix)",
    summary: {
      de: "Chat auf Basis des offenen Matrix-Protokolls, mit der Möglichkeit, mit anderen Häusern föderiert zu kommunizieren. Im deutschen öffentlichen Sektor mehrfach im Einsatz.",
      en: "Chat built on the open Matrix protocol, with federation between organizations. In use across parts of the German public sector.",
    },
    license: "apache",
    vendorCountry: "GB",
    ecosystem: "matrix",
    hostingModes: ["self_hosted", "eu_managed"],
    sovereignty: 5,
    maturity: 4,
    supportModel: "vendor_backed",
    deMarketPresence: 4,
    germanUiQuality: 4,
    publicSectorFit: 4,
    selfHostOpsLoad: 4,
    migrationComplexityBase: 3,
    trainingLoad: 3,
    seatScalability: {
      comfortableUpTo: 2000,
      notes: {
        de: "Der Betrieb des Servers verlangt mehr Aufmerksamkeit als bei einfacheren Chatlösungen, besonders bei vielen großen Räumen. Föderation ist ein echter Vorteil, wenn mit anderen Verwaltungen kommuniziert wird.",
        en: "Running the server demands more attention than simpler chat systems, especially with many large rooms. Federation is a genuine advantage when communicating with other authorities.",
      },
    },
    coexistence: "partial",
    rollbackDifficulty: 3,
    aiSuitability: { hasNativeAi: false, localAiFriendly: 3 },
    prerequisites: ["identity-directory", "communication-policy"],
    sources: ["https://element.io/", "https://matrix.org/docs/"],
  }),
  target({
    id: "mattermost",
    category: "chat_video",
    name: "Mattermost",
    summary: {
      de: "Kanalbasierter Chat mit vertrauter Bedienung und vergleichsweise einfachem Betrieb.",
      en: "Channel-based chat with familiar handling and comparatively simple operation.",
    },
    license: "open_core",
    vendorCountry: "US",
    hostingModes: ["self_hosted", "eu_managed"],
    sovereignty: 4,
    maturity: 4,
    supportModel: "commercial_available",
    deMarketPresence: 3,
    germanUiQuality: 4,
    publicSectorFit: 3,
    selfHostOpsLoad: 2,
    migrationComplexityBase: 2,
    trainingLoad: 2,
    seatScalability: {
      comfortableUpTo: 5000,
      notes: {
        de: "Auch bei vielen Konten gut beherrschbar. Einzelne Funktionen sind der kostenpflichtigen Ausgabe vorbehalten.",
        en: "Manageable even with many accounts. Some features are reserved for the paid edition.",
      },
    },
    coexistence: "partial",
    rollbackDifficulty: 2,
    aiSuitability: { hasNativeAi: false, localAiFriendly: 3 },
    prerequisites: ["identity-directory", "communication-policy"],
    sources: ["https://mattermost.com/", "https://docs.mattermost.com/"],
  }),
  target({
    id: "nextcloud-talk",
    category: "chat_video",
    name: "Nextcloud Talk",
    summary: {
      de: "Chat und Videogespräche innerhalb einer bereits vorhandenen Nextcloud-Installation. Für kleinere Häuser oft der pragmatischste Weg.",
      en: "Chat and video calls inside an existing Nextcloud install. Often the most pragmatic route for smaller organizations.",
    },
    license: "agpl",
    vendorCountry: "DE",
    ecosystem: "nextcloud",
    hostingModes: ["self_hosted", "eu_managed"],
    sovereignty: 5,
    maturity: 3,
    supportModel: "vendor_backed",
    deMarketPresence: 4,
    germanUiQuality: 5,
    publicSectorFit: 3,
    selfHostOpsLoad: 3,
    migrationComplexityBase: 2,
    trainingLoad: 2,
    seatScalability: {
      comfortableUpTo: 300,
      notes: {
        de: "Für größere Videokonferenzen ist ein zusätzlicher Medienserver erforderlich. Ohne diesen Schritt sind Gruppengespräche nur in kleinem Rahmen tragfähig — das wird bei der Planung häufig übersehen.",
        en: "Larger video meetings require an additional media server. Without that step, group calls only hold up at small scale — a step frequently missed during planning.",
      },
    },
    coexistence: "good",
    rollbackDifficulty: 2,
    aiSuitability: { hasNativeAi: true, localAiFriendly: 4 },
    prerequisites: ["file-platform"],
    sources: ["https://nextcloud.com/talk/", "https://docs.nextcloud.com/"],
  }),
  target({
    id: "bigbluebutton",
    category: "chat_video",
    name: "BigBlueButton",
    summary: {
      de: "Videokonferenz mit Schwerpunkt auf Unterricht und moderierten Veranstaltungen. An Schulen weit verbreitet.",
      en: "Video conferencing focused on teaching and moderated sessions. Widely used in schools.",
    },
    license: "lgpl",
    vendorCountry: "CA",
    hostingModes: ["self_hosted", "eu_managed"],
    sovereignty: 4,
    maturity: 4,
    supportModel: "commercial_available",
    deMarketPresence: 4,
    germanUiQuality: 4,
    publicSectorFit: 4,
    selfHostOpsLoad: 4,
    migrationComplexityBase: 3,
    trainingLoad: 2,
    seatScalability: {
      comfortableUpTo: 1000,
      notes: {
        de: "Maßgeblich ist die Zahl gleichzeitiger Teilnehmender, nicht die Zahl der Konten. Der Bedarf an Rechenleistung und Bandbreite ist erheblich und sollte vorab gerechnet werden.",
        en: "Concurrent participants matter, not account counts. Compute and bandwidth needs are substantial and should be sized in advance.",
      },
    },
    coexistence: "good",
    rollbackDifficulty: 2,
    aiSuitability: { hasNativeAi: false, localAiFriendly: 2 },
    prerequisites: ["network-capacity"],
    sources: ["https://bigbluebutton.org/", "https://docs.bigbluebutton.org/"],
  }),
  target({
    id: "jitsi-meet",
    category: "chat_video",
    name: "Jitsi Meet",
    summary: {
      de: "Videokonferenz ohne Konten und mit sehr niedriger Einstiegshürde. Gut geeignet für Gespräche mit Externen.",
      en: "Video conferencing without accounts and with a very low barrier to entry. Well suited to calls with external participants.",
    },
    license: "apache",
    vendorCountry: "US",
    hostingModes: ["self_hosted", "eu_managed"],
    sovereignty: 4,
    maturity: 4,
    supportModel: "community",
    deMarketPresence: 4,
    germanUiQuality: 4,
    publicSectorFit: 3,
    selfHostOpsLoad: 3,
    migrationComplexityBase: 1,
    trainingLoad: 1,
    seatScalability: {
      comfortableUpTo: 500,
      notes: {
        de: "Sehr geringe Einstiegshürde, weil Gäste kein Konto brauchen. Bei großen Runden stößt die Übertragungsqualität ohne zusätzliche Serverkomponenten an Grenzen.",
        en: "Very low barrier since guests need no account. Quality in large meetings hits limits without additional server components.",
      },
    },
    coexistence: "good",
    rollbackDifficulty: 1,
    aiSuitability: { hasNativeAi: false, localAiFriendly: 2 },
    prerequisites: ["network-capacity"],
    sources: ["https://jitsi.org/", "https://jitsi.github.io/handbook/"],
  }),

  // --- Intranet and wiki ----------------------------------------------------
  target({
    id: "bookstack",
    category: "intranet_wiki",
    name: "BookStack",
    summary: {
      de: "Wissensablage mit einfacher Gliederung in Regale, Bücher und Seiten. Sehr schnell verständlich, auch ohne Vorkenntnisse.",
      en: "Knowledge base organized into shelves, books and pages. Quick to grasp without prior experience.",
    },
    license: "mit",
    vendorCountry: "GB",
    hostingModes: ["self_hosted", "eu_managed"],
    sovereignty: 5,
    maturity: 4,
    supportModel: "community",
    deMarketPresence: 3,
    germanUiQuality: 4,
    publicSectorFit: 3,
    selfHostOpsLoad: 2,
    migrationComplexityBase: 2,
    trainingLoad: 1,
    seatScalability: {
      comfortableUpTo: 2000,
      notes: {
        de: "Die klare Gliederung hilft besonders dort, wo Inhalte von vielen Fachbereichen gepflegt werden und niemand die Struktur zentral betreut.",
        en: "The clear structure helps most where many departments maintain content and nobody curates the hierarchy centrally.",
      },
    },
    coexistence: "good",
    rollbackDifficulty: 1,
    aiSuitability: { hasNativeAi: false, localAiFriendly: 4 },
    prerequisites: ["identity-directory"],
    sources: ["https://www.bookstackapp.com/", "https://www.bookstackapp.com/docs/"],
  }),
  target({
    id: "xwiki",
    category: "intranet_wiki",
    name: "XWiki",
    summary: {
      de: "Umfangreiche Wiki-Plattform mit Strukturierungs- und Anwendungsfunktionen. Deckt auch anspruchsvollere Intranet-Anforderungen ab.",
      en: "A comprehensive wiki platform with structuring and application features, covering more demanding intranet requirements.",
    },
    license: "lgpl",
    vendorCountry: "FR",
    hostingModes: ["self_hosted", "eu_managed"],
    sovereignty: 5,
    maturity: 4,
    supportModel: "commercial_available",
    deMarketPresence: 3,
    germanUiQuality: 4,
    publicSectorFit: 4,
    selfHostOpsLoad: 3,
    migrationComplexityBase: 3,
    trainingLoad: 3,
    seatScalability: {
      comfortableUpTo: 5000,
      notes: {
        de: "Trägt auch große Inhaltsbestände. Der Funktionsumfang verlangt eine bewusste Strukturentscheidung zu Beginn, sonst wächst das Wiki unübersichtlich.",
        en: "Carries large content bases. Its breadth demands a deliberate structural decision up front, or the wiki sprawls.",
      },
    },
    coexistence: "good",
    rollbackDifficulty: 2,
    aiSuitability: { hasNativeAi: false, localAiFriendly: 4 },
    prerequisites: ["identity-directory", "content-ownership"],
    sources: [
      "https://www.xwiki.org/",
      "https://www.xwiki.org/xwiki/bin/view/Documentation/",
    ],
  }),
  target({
    id: "dokuwiki",
    category: "intranet_wiki",
    name: "DokuWiki",
    summary: {
      de: "Schlankes Wiki, das ohne Datenbank auskommt. Sehr geringer Betriebsaufwand, in Deutschland seit langem verbreitet.",
      en: "A lean wiki that works without a database. Very low operational overhead, long established in Germany.",
    },
    license: "gpl",
    vendorCountry: "DE",
    hostingModes: ["self_hosted", "eu_managed"],
    sovereignty: 5,
    maturity: 5,
    supportModel: "community",
    deMarketPresence: 4,
    germanUiQuality: 5,
    publicSectorFit: 3,
    selfHostOpsLoad: 1,
    migrationComplexityBase: 1,
    trainingLoad: 2,
    seatScalability: {
      comfortableUpTo: 500,
      notes: {
        de: "Der Verzicht auf eine Datenbank macht Sicherung und Umzug denkbar einfach. Bei sehr großen Inhaltsbeständen und vielen gleichzeitigen Zugriffen stößt dieser Ansatz an Grenzen.",
        en: "Skipping the database makes backup and relocation remarkably simple. Very large content bases with many concurrent readers strain the approach.",
      },
    },
    coexistence: "good",
    rollbackDifficulty: 1,
    aiSuitability: { hasNativeAi: false, localAiFriendly: 3 },
    prerequisites: [],
    sources: ["https://www.dokuwiki.org/", "https://www.dokuwiki.org/manual"],
  }),
];
