import { target } from "./_target";
import type { TargetTool } from "../../schema";

/**
 * Forms/surveys, CRM and DMS/archive.
 *
 * CRM and DMS are marked `focused` at the category level. The German DMS and
 * archiving market is fragmented and entangled with retention law, so lokal
 * deliberately covers a narrow, defensible slice and says so, rather than
 * implying the same research depth as the core categories.
 */
export const recordsTargets: TargetTool[] = [
  // --- Forms and surveys ----------------------------------------------------
  target({
    id: "limesurvey",
    category: "forms_surveys",
    name: "LimeSurvey",
    summary: {
      de: "Umfangreiche Umfragesoftware mit vielen Fragetypen und Auswertungsmöglichkeiten. Deutscher Anbieter, im Bildungs- und Verwaltungsumfeld verbreitet.",
      en: "Comprehensive survey software with many question types and analysis options. German vendor, common in education and administration.",
    },
    license: "gpl",
    vendorCountry: "DE",
    hostingModes: ["self_hosted", "eu_managed"],
    sovereignty: 5,
    maturity: 4,
    supportModel: "commercial_available",
    deMarketPresence: 4,
    germanUiQuality: 5,
    publicSectorFit: 4,
    selfHostOpsLoad: 2,
    migrationComplexityBase: 2,
    trainingLoad: 3,
    seatScalability: {
      comfortableUpTo: 2000,
      notes: {
        de: "Maßgeblich ist die Zahl der Befragten je Erhebung, nicht die Zahl der Beschäftigten. Wenige Personen erstellen Umfragen, viele beantworten sie.",
        en: "Respondents per survey matter, not staff count. Few people build surveys; many answer them.",
      },
    },
    coexistence: "good",
    rollbackDifficulty: 2,
    aiSuitability: { hasNativeAi: false, localAiFriendly: 3 },
    prerequisites: [],
    sources: ["https://www.limesurvey.org/", "https://manual.limesurvey.org/"],
  }),
  target({
    id: "nextcloud-forms",
    category: "forms_surveys",
    name: "Nextcloud Forms",
    summary: {
      de: "Einfache Formulare und Abfragen innerhalb einer vorhandenen Nextcloud. Deckt den Alltagsbedarf ohne zusätzliches System.",
      en: "Simple forms and polls inside an existing Nextcloud. Covers everyday needs without a further system.",
    },
    license: "agpl",
    vendorCountry: "DE",
    ecosystem: "nextcloud",
    hostingModes: ["self_hosted", "eu_managed"],
    sovereignty: 5,
    maturity: 3,
    supportModel: "vendor_backed",
    deMarketPresence: 4,
    germanUiQuality: 5,
    publicSectorFit: 3,
    selfHostOpsLoad: 1,
    migrationComplexityBase: 1,
    trainingLoad: 1,
    seatScalability: {
      comfortableUpTo: 1000,
      notes: {
        de: "Für Anmeldungen und interne Rückmeldungen ausreichend. Für förmliche Anträge oder komplexe Befragungen ist der Funktionsumfang zu schmal.",
        en: "Sufficient for registrations and internal feedback. Too narrow for formal applications or complex surveys.",
      },
    },
    coexistence: "good",
    rollbackDifficulty: 1,
    aiSuitability: { hasNativeAi: false, localAiFriendly: 2 },
    prerequisites: ["file-platform"],
    sources: ["https://apps.nextcloud.com/apps/forms", "https://docs.nextcloud.com/"],
  }),
  target({
    id: "formbricks",
    category: "forms_surveys",
    name: "Formbricks",
    summary: {
      de: "Neuere Umfrage- und Feedbackplattform mit moderner Bedienung.",
      en: "A newer survey and feedback platform with a modern interface.",
    },
    license: "agpl",
    vendorCountry: "DE",
    hostingModes: ["self_hosted", "eu_managed"],
    sovereignty: 4,
    maturity: 3,
    supportModel: "commercial_available",
    deMarketPresence: 2,
    germanUiQuality: 4,
    publicSectorFit: 2,
    selfHostOpsLoad: 3,
    migrationComplexityBase: 2,
    trainingLoad: 2,
    seatScalability: {
      comfortableUpTo: 1000,
      notes: {
        de: "Angenehm in der Bedienung, aber jünger und im deutschen Verwaltungsumfeld noch wenig erprobt.",
        en: "Pleasant to use, but younger and not yet widely proven in German administration.",
      },
    },
    coexistence: "good",
    rollbackDifficulty: 2,
    aiSuitability: { hasNativeAi: false, localAiFriendly: 3 },
    prerequisites: [],
    sources: ["https://formbricks.com/", "https://formbricks.com/docs"],
  }),

  target({
    id: "openflow",
    category: "forms_surveys",
    name: "OpenFlow (Vidual Labs)",
    summary: {
      de: "Mehrstufige Formulare im Stil von Typeform, ausgelegt auf Lead-Erfassung über Landingpages. Per Docker schnell selbst betrieben, mit deutscher Sprachfassung für Ausfüllende. Zu beachten: Die Lizenz enthält Nutzungseinschränkungen und entspricht damit nicht der klassischen Open-Source-Definition — für öffentliche Stellen ist das vor einer Einführung zu prüfen. Das Projekt ist zudem sehr jung und hat bislang kaum Verbreitung.",
      en: "Multi-step Typeform-style forms aimed at landing-page lead capture. Quick to self-host via Docker, with a German language option for respondents. Note: the license carries field-of-use restrictions and therefore does not meet the classic open-source definition — public bodies should check this before adopting. The project is also very young with little adoption so far.",
    },
    license: "source_available",
    hostingModes: ["self_hosted"],
    sovereignty: 4,
    maturity: 1,
    supportModel: "community",
    deMarketPresence: 1,
    germanUiQuality: 3,
    publicSectorFit: 1,
    selfHostOpsLoad: 2,
    migrationComplexityBase: 2,
    trainingLoad: 1,
    seatScalability: {
      comfortableUpTo: 200,
      notes: {
        de: "Auf Lead-Erfassung ausgelegt, nicht auf interne Befragungen oder förmliche Anträge. Die Datenhaltung in SQLite ist für kleine Installationen angemessen, setzt größeren Erhebungen aber früh Grenzen.",
        en: "Built for lead capture, not internal surveys or formal applications. SQLite storage suits small installs but limits larger data collection early.",
      },
    },
    coexistence: "good",
    rollbackDifficulty: 1,
    aiSuitability: { hasNativeAi: false, localAiFriendly: 2 },
    prerequisites: [],
    sources: ["https://github.com/vidual-labs/openflow"],
  }),

  // --- CRM (focused coverage) -----------------------------------------------
  target({
    id: "espocrm",
    category: "crm",
    name: "EspoCRM",
    summary: {
      de: "Schlanke Kontakt- und Vorgangsverwaltung, die sich ohne großen Aufwand einführen lässt.",
      en: "Lean contact and activity management that can be introduced without major effort.",
    },
    license: "agpl",
    hostingModes: ["self_hosted", "eu_managed"],
    sovereignty: 5,
    maturity: 4,
    supportModel: "commercial_available",
    deMarketPresence: 2,
    germanUiQuality: 3,
    publicSectorFit: 2,
    selfHostOpsLoad: 2,
    migrationComplexityBase: 3,
    trainingLoad: 3,
    seatScalability: {
      comfortableUpTo: 500,
      notes: {
        de: "Für Vereine und kleinere Betriebe gut geeignet. Maßgeblich ist die Zahl der pflegenden Personen, nicht die Zahl der Kontakte.",
        en: "Well suited to associations and smaller businesses. The number of people maintaining records matters, not the number of contacts.",
      },
    },
    coexistence: "good",
    rollbackDifficulty: 3,
    aiSuitability: { hasNativeAi: false, localAiFriendly: 2 },
    prerequisites: ["data-inventory"],
    sources: ["https://www.espocrm.com/", "https://docs.espocrm.com/"],
  }),
  target({
    id: "suitecrm",
    category: "crm",
    name: "SuiteCRM",
    summary: {
      de: "Umfangreicheres CRM mit breitem Funktionsumfang und entsprechend höherem Einführungsaufwand.",
      en: "A more comprehensive CRM with broad functionality and correspondingly higher introduction effort.",
    },
    license: "agpl",
    vendorCountry: "GB",
    hostingModes: ["self_hosted", "eu_managed"],
    sovereignty: 5,
    maturity: 4,
    supportModel: "commercial_available",
    deMarketPresence: 2,
    germanUiQuality: 3,
    publicSectorFit: 2,
    selfHostOpsLoad: 3,
    migrationComplexityBase: 4,
    trainingLoad: 4,
    seatScalability: {
      comfortableUpTo: 1000,
      notes: {
        de: "Deckt anspruchsvollere Vertriebsprozesse ab. Ohne klare fachliche Federführung bleibt die Einführung häufig stecken.",
        en: "Covers more demanding sales processes. Without clear business ownership, introductions frequently stall.",
      },
    },
    coexistence: "partial",
    rollbackDifficulty: 4,
    aiSuitability: { hasNativeAi: false, localAiFriendly: 2 },
    prerequisites: ["data-inventory", "process-ownership"],
    sources: ["https://suitecrm.com/", "https://docs.suitecrm.com/"],
  }),

  // --- DMS and archive (focused coverage) -----------------------------------
  target({
    id: "paperless-ngx",
    category: "dms_archive",
    name: "Paperless-ngx",
    summary: {
      de: "Erfasst und durchsucht eingescannte Dokumente mit Texterkennung. Sehr geeignet, um Papierablagen auffindbar zu machen — ausdrücklich kein Ersatz für ein rechtssicheres Archivsystem.",
      en: "Captures and indexes scanned documents with text recognition. Well suited to making paper filing searchable — explicitly not a substitute for a legally compliant archive system.",
    },
    license: "gpl",
    hostingModes: ["self_hosted"],
    sovereignty: 5,
    maturity: 4,
    supportModel: "community",
    deMarketPresence: 3,
    germanUiQuality: 4,
    publicSectorFit: 2,
    selfHostOpsLoad: 2,
    migrationComplexityBase: 2,
    trainingLoad: 2,
    seatScalability: {
      comfortableUpTo: 300,
      notes: {
        de: "Ausgezeichnet für Auffindbarkeit im Alltag. Aufbewahrungspflichten, Unveränderbarkeit und Aussonderung sind gesondert und mit fachkundiger Beratung zu klären.",
        en: "Excellent for day-to-day retrievability. Retention duties, immutability and disposal must be settled separately with qualified advice.",
      },
    },
    coexistence: "good",
    rollbackDifficulty: 2,
    aiSuitability: {
      hasNativeAi: false,
      localAiFriendly: 4,
      notes: {
        de: "Ein durchsuchbarer Dokumentenbestand ist die übliche Voraussetzung dafür, dass interne Dokumentenrecherche mit KI überhaupt sinnvoll wird.",
        en: "A searchable document base is the usual precondition for internal document Q&A with AI to make any sense.",
      },
    },
    prerequisites: ["data-inventory", "retention-review"],
    sources: [
      "https://docs.paperless-ngx.com/",
      "https://github.com/paperless-ngx/paperless-ngx",
    ],
  }),
  target({
    id: "mayan-edms",
    category: "dms_archive",
    name: "Mayan EDMS",
    summary: {
      de: "Dokumentenmanagement mit Arbeitsabläufen, Metadaten und Rechtevergabe. Deutlich formaler als eine reine Scanablage.",
      en: "Document management with workflows, metadata and permissions. Markedly more formal than a plain scan repository.",
    },
    license: "apache",
    hostingModes: ["self_hosted"],
    sovereignty: 5,
    maturity: 3,
    supportModel: "community",
    deMarketPresence: 2,
    germanUiQuality: 3,
    publicSectorFit: 2,
    selfHostOpsLoad: 4,
    migrationComplexityBase: 4,
    trainingLoad: 4,
    seatScalability: {
      comfortableUpTo: 500,
      notes: {
        de: "Trägt formalisierte Ablageprozesse. Betrieb und Einarbeitung sind anspruchsvoll und sollten nicht nebenher erfolgen.",
        en: "Supports formalized filing processes. Operation and onboarding are demanding and should not be attempted on the side.",
      },
    },
    coexistence: "partial",
    rollbackDifficulty: 4,
    aiSuitability: { hasNativeAi: false, localAiFriendly: 3 },
    prerequisites: ["data-inventory", "retention-review", "process-ownership"],
    sources: ["https://www.mayan-edms.com/", "https://docs.mayan-edms.com/"],
  }),
];
