import { target } from "./_target";
import type { TargetTool } from "../../schema";

/** Project management and helpdesk — where process discipline matters more than features. */
export const workTargets: TargetTool[] = [
  // --- Project management ---------------------------------------------------
  target({
    id: "openproject",
    category: "project_management",
    name: "OpenProject",
    summary: {
      de: "Projektverwaltung mit Terminplanung, Aufgaben und Berichten. Deutscher Anbieter mit Erfahrung im öffentlichen Sektor.",
      en: "Project management with scheduling, tasks and reporting. German vendor with public-sector experience.",
    },
    license: "gpl",
    vendorCountry: "DE",
    hostingModes: ["self_hosted", "eu_managed"],
    sovereignty: 5,
    maturity: 4,
    supportModel: "vendor_backed",
    deMarketPresence: 5,
    germanUiQuality: 5,
    publicSectorFit: 4,
    selfHostOpsLoad: 3,
    migrationComplexityBase: 3,
    trainingLoad: 3,
    seatScalability: {
      comfortableUpTo: 2000,
      notes: {
        de: "Deckt auch formalere Projektstrukturen ab. Der Funktionsumfang lohnt sich erst, wenn tatsächlich nach Projekten gearbeitet wird — sonst wirkt das Werkzeug schwerfällig.",
        en: "Covers more formal project structures. The breadth only pays off where work is genuinely organized in projects; otherwise it feels heavy.",
      },
    },
    coexistence: "good",
    rollbackDifficulty: 3,
    aiSuitability: { hasNativeAi: false, localAiFriendly: 3 },
    prerequisites: ["identity-directory", "process-ownership"],
    sources: ["https://www.openproject.org/", "https://www.openproject.org/docs/"],
  }),
  target({
    id: "vikunja",
    category: "project_management",
    name: "Vikunja",
    summary: {
      de: "Schlanke Aufgabenverwaltung mit Listen, Tafeln und Terminen. Geeignet, wo eine vollwertige Projektsoftware zu viel wäre.",
      en: "Lean task management with lists, boards and due dates. Suitable where full project software would be overkill.",
    },
    license: "agpl",
    vendorCountry: "DE",
    hostingModes: ["self_hosted", "eu_managed"],
    sovereignty: 5,
    maturity: 3,
    supportModel: "community",
    deMarketPresence: 2,
    germanUiQuality: 4,
    publicSectorFit: 2,
    selfHostOpsLoad: 1,
    migrationComplexityBase: 1,
    trainingLoad: 1,
    seatScalability: {
      comfortableUpTo: 300,
      notes: {
        de: "Sehr geringer Einstiegs- und Betriebsaufwand. Für Häuser mit formalen Berichtspflichten reicht der Funktionsumfang nicht aus.",
        en: "Very low entry and operating effort. Not sufficient where formal reporting duties apply.",
      },
    },
    coexistence: "good",
    rollbackDifficulty: 1,
    aiSuitability: { hasNativeAi: false, localAiFriendly: 2 },
    prerequisites: [],
    sources: ["https://vikunja.io/", "https://vikunja.io/docs/"],
  }),
  target({
    id: "redmine",
    category: "project_management",
    name: "Redmine",
    summary: {
      de: "Seit langem etablierte Projekt- und Vorgangsverwaltung. Sehr stabil, in der Bedienung altmodisch.",
      en: "Long-established project and issue tracking. Very stable, dated in its interface.",
    },
    license: "gpl",
    hostingModes: ["self_hosted", "eu_managed"],
    sovereignty: 5,
    maturity: 5,
    supportModel: "community",
    deMarketPresence: 3,
    germanUiQuality: 4,
    publicSectorFit: 3,
    selfHostOpsLoad: 2,
    migrationComplexityBase: 2,
    trainingLoad: 3,
    seatScalability: {
      comfortableUpTo: 2000,
      notes: {
        de: "Bewährt und anspruchslos im Betrieb. Die in die Jahre gekommene Oberfläche erhöht den Schulungsaufwand bei weniger technikaffinen Beschäftigten.",
        en: "Proven and undemanding to run. The dated interface raises training effort for less technical staff.",
      },
    },
    coexistence: "good",
    rollbackDifficulty: 2,
    aiSuitability: { hasNativeAi: false, localAiFriendly: 2 },
    prerequisites: ["identity-directory"],
    sources: ["https://www.redmine.org/", "https://www.redmine.org/guide"],
  }),

  // --- Helpdesk -------------------------------------------------------------
  target({
    id: "zammad",
    category: "helpdesk",
    name: "Zammad",
    summary: {
      de: "Ticketsystem mit moderner Oberfläche und guter Anbindung an E-Mail und Telefonie. Deutscher Anbieter, im öffentlichen Sektor häufig anzutreffen.",
      en: "Ticketing with a modern interface and solid email and telephony integration. German vendor, frequently seen in the public sector.",
    },
    license: "agpl",
    vendorCountry: "DE",
    hostingModes: ["self_hosted", "eu_managed"],
    sovereignty: 5,
    maturity: 4,
    supportModel: "vendor_backed",
    deMarketPresence: 5,
    germanUiQuality: 5,
    publicSectorFit: 4,
    selfHostOpsLoad: 3,
    migrationComplexityBase: 3,
    trainingLoad: 2,
    seatScalability: {
      comfortableUpTo: 1000,
      notes: {
        de: "Maßgeblich ist die Zahl der Bearbeitenden, nicht die Zahl der Anfragenden. Ein Haus mit 500 Beschäftigten braucht oft nur ein Dutzend Lizenzplätze im Ticketsystem.",
        en: "Agent count matters, not requester count. A 500-person organization often needs only a dozen seats in the ticket system.",
      },
    },
    coexistence: "good",
    rollbackDifficulty: 3,
    aiSuitability: {
      hasNativeAi: false,
      localAiFriendly: 4,
      notes: {
        de: "Die strukturierten Vorgangsdaten eignen sich gut für Vorsortierung und Zusammenfassungen, sofern eine fachliche Prüfung vorgeschaltet bleibt.",
        en: "Structured ticket data suits triage and summarization well, provided human review stays in front of it.",
      },
    },
    prerequisites: ["identity-directory", "process-ownership"],
    sources: ["https://zammad.com/", "https://docs.zammad.org/"],
  }),
  target({
    id: "otobo",
    category: "helpdesk",
    name: "OTOBO",
    summary: {
      de: "Ticketsystem in der Tradition von OTRS, mit ausgeprägten Funktionen für formale Abläufe und Berichtspflichten.",
      en: "Ticketing in the OTRS tradition, with pronounced support for formal workflows and reporting duties.",
    },
    license: "gpl",
    vendorCountry: "DE",
    hostingModes: ["self_hosted", "eu_managed"],
    sovereignty: 5,
    maturity: 4,
    supportModel: "commercial_available",
    deMarketPresence: 4,
    germanUiQuality: 5,
    publicSectorFit: 4,
    selfHostOpsLoad: 4,
    migrationComplexityBase: 4,
    trainingLoad: 4,
    seatScalability: {
      comfortableUpTo: 3000,
      notes: {
        de: "Stark bei formalisierten Verfahren und Nachweispflichten. Einrichtung und Schulung sind deutlich aufwendiger als bei schlankeren Systemen.",
        en: "Strong for formalized procedures and audit duties. Setup and training are markedly heavier than in leaner systems.",
      },
    },
    coexistence: "partial",
    rollbackDifficulty: 4,
    aiSuitability: { hasNativeAi: false, localAiFriendly: 3 },
    prerequisites: ["identity-directory", "process-ownership"],
    sources: ["https://otobo.io/", "https://doc.otobo.org/"],
  }),
  target({
    id: "glpi",
    category: "helpdesk",
    name: "GLPI",
    summary: {
      de: "Verbindet Ticketsystem und Inventarverwaltung der IT-Ausstattung in einem Werkzeug.",
      en: "Combines ticketing with IT asset inventory in one tool.",
    },
    license: "gpl",
    vendorCountry: "FR",
    hostingModes: ["self_hosted", "eu_managed"],
    sovereignty: 5,
    maturity: 4,
    supportModel: "commercial_available",
    deMarketPresence: 3,
    germanUiQuality: 3,
    publicSectorFit: 3,
    selfHostOpsLoad: 3,
    migrationComplexityBase: 3,
    trainingLoad: 3,
    seatScalability: {
      comfortableUpTo: 2000,
      notes: {
        de: "Besonders sinnvoll, wenn ohnehin eine Inventarverwaltung fehlt und beides zusammen eingeführt werden soll.",
        en: "Particularly sensible where asset inventory is missing anyway and both should be introduced together.",
      },
    },
    coexistence: "good",
    rollbackDifficulty: 3,
    aiSuitability: { hasNativeAi: false, localAiFriendly: 3 },
    prerequisites: ["identity-directory"],
    sources: ["https://glpi-project.org/", "https://glpi-project.org/documentation/"],
  }),
];
